<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="course_table.xsl"?>
<!DOCTYPE course_table [
<!ELEMENT course_table (course)*>
<!ELEMENT course (name , teaID , description)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT teaID (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ATTLIST course id ID #REQUIRED>
]>
<course_table>

    <course id="c001">        
        <name>Discrete mathematics 2</name>  
        <teaID>t001</teaID>        
        <description>no description-change</description>
    </course>

    <course id="c002">        
        <name>Numeric Calculation</name>  
        <teaID>t001</teaID>
        <description>Numeric Calculation？？？</description>
    </course>

    <course id="c003">        
        <name>Discrete mathematics 1</name>  
        <teaID>t002</teaID>
        <description>no description</description>
    </course>

    <course id="c004">        
        <name>Software Engineering</name>  
        <teaID>t002</teaID>
        <description>no description</description>
    </course>

    <course id="c005">        
        <name>Artificial Intelligence</name>  
        <teaID>t002</teaID>
        <description>no description</description>
    </course>

    <course id="c006">        
        <name>Advanced Mathematics</name>  
        <teaID>t003</teaID>
        <description>no description</description>
    </course>

<course id="ct001Hea"><name>Head First XML</name><teaID>t001</teaID><description>XMLXML!!!</description></course></course_table>
